config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resource :session
  resources :passwords, param: :token
  root 'static_pages#home'
  get 'dashboard', to: 'static_pages#dashboard'
  resources :events
  resources :contacts

  namespace :api do 
    namespace :v1 do 
      resources :contacts 
      resources :events
    end 
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  allow_unauthenticated_access only: %i[ home ]
  def home
  end

  def dashboard
    @active_contacts = Contact.where(status: 'Active').count
    @inactive_contacts = Contact.where(status: 'Inactive').count
    @deactivated_contacts = Contact.where(status: 'Deactivated').count

    @contact_count = Contact.count_records
    @event_count = Event.count_records
    @video_count = Video.count_records
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/dashboard.html.erb
<div>
<h1 class="font-bold text-4xl">StaticPages#dashboard</h1></br>

<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 p-4">
  <div class="bg-blue-100 p-6 rounded-lg shadow-md w-32 h-32 flex items-center justify-center">
    <p>Inactive: <%= @inactive_contacts %></p>
  </div>
  <div class="bg-green-100 p-6 rounded-lg shadow-md w-32 h-32 flex items-center justify-center">
    <p>Active: <%= @active_contacts %></p>
  </div>
  <div class="bg-red-100 p-6 rounded-lg shadow-md w-32 h-32 flex items-center justify-center">
    <p>Deactivated: <%= @deactivated_contacts %></p>
  </div>
  <div class="bg-yellow-100 p-6 rounded-lg shadow-md w-32 h-32 flex items-center justify-center">
    <p>Contact count: <%= @contact_count %></p>
  </div>
  <div class="bg-purple-100 p-6 rounded-lg shadow-md w-32 h-32 flex items-center justify-center">
    <p>Event count: <%= @event_count %></p>
  </div>
  <div class="bg-purple-100 p-6 rounded-lg shadow-md w-32 h-32 flex items-center justify-center">
    <p>Video count: <%= @video_count %></p>
  </div>
</div>
</div>

app/views/static_pages/home.html.erb
<div>
  <h1 class="font-bold text-4xl">StaticPages#home</h1>
  <p>Find me in app/views/static_pages/home.html.erb</p>
  <hr />
  
  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 p-4">
  <div class="w-32 h-32 flex items-center justify-center rounded-lg shadow-md">
    <%= link_to 'Contacts', contacts_path %>
  </div>
  <div class="w-32 h-32 flex items-center justify-center rounded-lg shadow-md">
    <%= link_to 'Events', events_path %>
  </div>
  <div class="w-32 h-32 flex items-center justify-center rounded-lg shadow-md">
    <%= link_to 'Dashboard', dashboard_path %>
  </div>
  <div class="w-32 h-32 flex items-center justify-center rounded-lg shadow-md">
    <%= link_to 'Videos', videos_path %>
  </div>
</div>