config/routes.rb
Rails.application.routes.draw do
  resources :videos
  resource :session
  resources :passwords, param: :token
  root 'static_pages#home'
  get 'dashboard', to: 'static_pages#dashboard'
  resources :events
  resources :contacts

  namespace :api do 
    namespace :v1 do 
      resources :contacts 
      resources :events
    end 
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/contact.rb
require 'csv'
require 'caxlsx'

class Contact < ApplicationRecord
    has_many :events, dependent: :destroy

    def self.to_csv
        attributes = %w{id first_name last_name email phone city state country status}
    
        ::CSV.generate(headers: true) do |csv|
          csv << attributes
    
          all.find_each do |contact|
            csv << attributes.map{ |attr| contact.send(attr) }
          end
        end
      end
    
      def self.to_xlsx
        p = Axlsx::Package.new
        wb = p.workbook
        wb.add_worksheet(name: "Contacts") do |sheet|
          sheet.add_row ["ID", "First Name", "Last Name", "Email", "Phone", "City", "State", "Country", "Status"]
          all.find_each do |contact|
            sheet.add_row [contact.id, contact.first_name, contact.last_name, contact.email, contact.phone, contact.city, contact.state, contact.country, contact.status]
          end
        end
        p.to_stream.read
    end

    def full_name 
        "#{first_name} #{last_name}" 
    end

    def location
        "#{city}, #{state}, #{country}"
    end

    def self.count_records
        self.count
    end
end

app/controllers/api/v1/contacts_controller.rb
class Api::V1::ContactsController < ApplicationController
    before_action :set_contact, only: [:show, :update, :destroy]
    skip_before_action :verify_authenticity_token
  
    # GET /api/v1/contacts
    def index
      @contacts = Contact.all
      render json: JSON.pretty_generate(@contacts.as_json)
    end
  
    # GET /api/v1/contacts/:id
    def show
      render json: @contact
    end
  
    # POST /api/v1/contacts
    def create
      @contact = Contact.new(contact_params)
      if @contact.save
        render json: JSON.pretty_generate(@contact.as_json), status: :created, location: api_v1_contact_url(@contact)
      else
        render json: JSON.pretty_generate(@contact.errors.as_json), status: :unprocessable_entity
      end
    end
  
    # PATCH/PUT /api/v1/contacts/:id
    def update
      if @contact.update(contact_params)
        render json: @contact
      else
        render json: @contact.errors, status: :unprocessable_entity
      end
    end
  
    # DELETE /api/v1/contacts/:id
    def destroy
      @contact.destroy
    end
  
    private
  
    def set_contact
      @contact = Contact.find(params[:id])
    end
  
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone, :city, :state, :country, :status)
    end
  end
  

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html
      format.csv { send_data @contacts.to_csv, filename: "contacts-#{Date.today}.csv" }
      format.xlsx { send_data @contacts.to_xlsx, filename: "contacts-#{Date.today}.xlsx" }
    end
  end

  # GET /contacts/1 or /contacts/1.json
  def show
    @events = @contact.events
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy!

    respond_to do |format|
      format.html { redirect_to contacts_path, status: :see_other, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.expect(contact: [ :first_name, :last_name, :email, :phone, :city, :state, :country, :status ])
    end
end

app/helpers/api/v1/contacts_helper.rb
module Api::V1::ContactsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">First name:</strong>
    <%= contact.first_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Last name:</strong>
    <%= contact.last_name %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Status:</strong>
    <%= contact.status %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= contact.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone:</strong>
    <%= contact.phone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Location:</strong>
    <%= contact.location %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, class: "contents") do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.text_field :status, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :city %>
    <%= form.text_field :city, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :state %>
    <%= form.text_field :state, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :Country %>
    <%= form.text_field :country, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing contact</h1>

  <%= render "form", contact: @contact %>

  <%= link_to "Show this contact", @contact, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to contacts", contacts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/contacts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Contacts" %>

  <div class="flex justify-between items-center mb-5">
    <h1 class="font-bold text-4xl">Contacts</h1>
    <%= link_to "New contact", new_contact_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <%= link_to 'Export to CSV', contacts_path(format: :csv) %>
    <%= link_to 'Export to Excel', contacts_path(format: :xlsx) %>
  </div>

  <div id="contacts" class="min-w-full overflow-x-auto">
    <table class="table-auto border-collapse w-full text-left bg-white shadow rounded-lg">
      <thead>
        <tr class="bg-gray-100 text-gray-700">
          <th class="py-2 px-4 border-b">Full Name</th>
          <th class="py-2 px-4 border-b">Status</th>
          <th class="py-2 px-4 border-b">Email</th>
          <th class="py-2 px-4 border-b">Phone</th>
          <th class="py-2 px-4 border-b">Location</th>
          <th class="py-2 px-4 border-b">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @contacts.each do |contact| %>
          <tr class="hover:bg-gray-50">
            <td class="py-2 px-4 border-b"><%= contact.full_name %></td>
            <td class="py-2 px-4 border-b"><%= contact.status %></td>
            <td class="py-2 px-4 border-b"><%= contact.email %></td>
            <td class="py-2 px-4 border-b"><%= contact.phone %></td>
            <td class="py-2 px-4 border-b"><%= contact.location %></td>
            <td class="py-2 px-4 border-b">
              <%= link_to "Show", contact, class: "ml-2 rounded-lg py-2 px-4 bg-gray-100 text-gray-700 inline-block font-medium" %>
              <%= link_to "Edit", edit_contact_path(contact), class: "ml-2 rounded-lg py-2 px-4 bg-blue-100 text-blue-700 inline-block font-medium" %>
              <%= link_to "Delete", contact, method: :delete, data: { confirm: "Are you sure?" }, class: "ml-2 rounded-lg py-2 px-4 bg-red-100 text-red-700 inline-block font-medium" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New contact</h1>

  <%= render "form", contact: @contact %>

  <%= link_to "Back to contacts", contacts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/contacts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @contact %>

    <%= link_to "Edit this contact", edit_contact_path(@contact), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to contacts", contacts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this contact", @contact, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>

    <div class="w-full"> 
      <h3 class="text-lg font-medium">
        Events for <%= @contact.full_name %>:</h3>
      <% if @contact.events.any? %> 
        <div id="events" class="min-w-full overflow-x-auto"> 
          <table class="table-auto border-collapse w-full text-left bg-white shadow rounded-lg"> 
            <thead> 
              <tr class="bg-gray-100 text-gray-700"> 
                <th class="py-2 px-4 border-b">Date</th> 
                <th class="py-2 px-4 border-b">Location</th> 
                <th class="py-2 px-4 border-b">Summary</th> 
                <th class="py-2 px-4 border-b">Actions</th> 
              </tr> 
            </thead> 
            <tbody> 
              <% @contact.events.each do |event| %> 
                <tr class="hover:bg-gray-50"> 
                  <td class="py-2 px-4 border-b"><%= event.date %></td> 
                  <td class="py-2 px-4 border-b"><%= event.location %></td> 
                  <td class="py-2 px-4 border-b"><%= event.summary %></td> 
                  <td class="py-2 px-4 border-b"> <%= link_to "Edit", edit_event_path(event), class: "ml-2 rounded-lg py-2 px-4 bg-blue-100 text-blue-700 inline-block font-medium" %> </td> 
                </tr> 
              <% end %> 
            </tbody> 
          </table> 
        </div> 
      <% else %> 
        <p class="py-2 px-3 bg-red-50 text-red-500 font-medium rounded-lg">No events found for this contact.</p> 
      <% end %> 
        <%= link_to "Add Event", new_event_path(contact_id: @contact.id), class: "mt-5 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
  </div>
</div>